# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

version: '2'
services:
 app:
  image: 'verchol/lets-chat:codefresh-sample'
  links:
    - mongo
  environment:
    - PORT=5000
  ports:
    - 5000:5000
 mongo:
  image: mongo

 test:
  image : nhoag/curl
  command: bash -c "sleep 5 && curl http://app:5000/" 
